language: python
python: "3.7.9"

notifications:      
  email: true

sudo: false 
env:
  global:
    - CODECOV_TOKEN: aa0c1c94-91a8-4af8-94f8-e2b5a08e30a7

before_install: 
  - pip install numpy 
  - pip install scipy
  - pip install pytest 
  - pip install matplotlib
  - pip install codecov 
  - pip install coverage

install:
  - python setup.py install

script: 
  - coverage run openpd/coverageTest.py

after_success:
  - codecov