language: python
python: "3.7"

notifications:      
  email: true

sudo: false 
env:
  global:
    - CODECOV_TOKEN: cbbdc9a4-93c2-485c-b5fc-ecfb2892cf4e

before_install: 
  - pip install numpy 
  - pip install scipy
  - pip install pytest 
  - pip install pytest-xdist
  - pip install matplotlib
  - pip install codecov 
  - pip install coverage

install:
  - python setup.py install

script: 
  - coverage run openpd/runTest.py

after_success:
  - codecov