language: python
python: "3.7"

notifications:      
  email: true

sudo: false 

before_install: 
  - pip install numpy 
  - pip install pytest 
  - pip install matplotlib

install: true 

script: 
  - python -m openpd.runTest
